# Generated by Django 2.2.13 on 2021-10-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut_adm', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pass_field', models.CharField(db_column='pass', max_length=50)),
                ('nombre_adm', models.CharField(max_length=50)),
                ('apat_adm', models.CharField(max_length=50)),
                ('amat_adm', models.CharField(max_length=50)),
                ('email_admin', models.CharField(max_length=50)),
                ('fono_admin', models.IntegerField()),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cli', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=50)),
                ('apaterno_cli', models.CharField(max_length=50)),
                ('amaterno_cli', models.CharField(max_length=50)),
                ('fono_cli', models.IntegerField()),
                ('email_cli', models.CharField(max_length=50)),
                ('saldo_cli', models.IntegerField()),
                ('pass_field', models.TextField(db_column='pass')),
                ('direccion_cliente', models.CharField(max_length=50)),
                ('convenio', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cli', models.CharField(max_length=50)),
                ('nom_cli', models.CharField(max_length=50)),
                ('nom_emp', models.CharField(max_length=50)),
                ('rut_emp', models.CharField(max_length=50)),
                ('tipo_suscrip', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'convenio',
            },
        ),
        migrations.CreateModel(
            name='EncCocina',
            fields=[
                ('id_enc_coc', models.AutoField(primary_key=True, serialize=False)),
                ('nom_enc_coc', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('exp_laboral', models.IntegerField()),
                ('email_enc_coc', models.EmailField(max_length=254)),
                ('contraseña1', models.CharField(max_length=100)),
                ('contraseña2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'enc_cocina',
            },
        ),
        migrations.CreateModel(
            name='EncConvenio',
            fields=[
                ('id_enc_conv', models.AutoField(primary_key=True, serialize=False)),
                ('rut_enc_conv', models.CharField(max_length=100)),
                ('nom_enc_conv', models.CharField(max_length=100)),
                ('ap_enc_conv', models.CharField(max_length=100)),
                ('email_enc_conv', models.EmailField(max_length=254)),
                ('contraseña1', models.CharField(max_length=100)),
                ('contraseña2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'enc_convenio',
            },
        ),
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.IntegerField()),
                ('id_plato', models.IntegerField()),
                ('fec_pedido', models.CharField(max_length=50)),
                ('total_pedido', models.IntegerField()),
                ('nom_plato', models.CharField(max_length=50)),
                ('nom_ing', models.CharField(max_length=50)),
                ('valor_ing', models.IntegerField()),
            ],
            options={
                'db_table': 'informes',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ing', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ing', models.CharField(max_length=50)),
                ('desc_ing', models.CharField(max_length=50)),
                ('tipo_ing', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ingrediente',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nom_plato', models.CharField(max_length=50)),
                ('valor_plato', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'plato',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('rol_local', models.CharField(max_length=50)),
                ('nom_proveedor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id_repartidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_repartidor', models.CharField(max_length=50)),
                ('apellido_repartidor', models.CharField(max_length=50)),
                ('patente_veh', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('contraseña1', models.CharField(max_length=100)),
                ('contraseña2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'repartidor',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id_restaurante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rest', models.CharField(max_length=50)),
                ('direccion_rest', models.CharField(max_length=50)),
                ('comuna_rest', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_suscrip', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_suscrip', models.CharField(max_length=50)),
                ('desc_suscrip', models.CharField(max_length=50)),
                ('administrador_rut_adm', models.ForeignKey(db_column='administrador_rut_adm', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.Administrador')),
                ('enc_convenio_id_enc_conv', models.ForeignKey(db_column='enc_convenio_id_enc_conv', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.EncConvenio')),
            ],
            options={
                'db_table': 'suscripción',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_pedido', models.CharField(max_length=50)),
                ('cliente_rut_cli', models.ForeignKey(db_column='cliente_rut_cli', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.Cliente')),
                ('restaurant_id_restaurante', models.ForeignKey(db_column='restaurant_id_restaurante', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.Restaurant')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rut_emp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_emp', models.CharField(max_length=50)),
                ('nom_gerente', models.CharField(max_length=50)),
                ('cant_trabajadores', models.IntegerField()),
                ('enc_convenio_id_enc_conv', models.ForeignKey(db_column='enc_convenio_id_enc_conv', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.EncConvenio')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id_cajero', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cajero', models.CharField(max_length=50)),
                ('restaurant_id_restaurante', models.ForeignKey(db_column='restaurant_id_restaurante', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.Restaurant')),
            ],
            options={
                'db_table': 'cajero',
            },
        ),
        migrations.CreateModel(
            name='Preparacin',
            fields=[
                ('id_prepa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('desc_preparacion', models.CharField(max_length=50)),
                ('lista_ing', models.CharField(max_length=50)),
                ('ingrediente_id_ing', models.ForeignKey(db_column='ingrediente_id_ing', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.Ingrediente')),
                ('plato_id_plato', models.ForeignKey(db_column='plato_id_plato', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.Plato')),
            ],
            options={
                'db_table': 'preparación',
                'unique_together': {('id_prepa', 'plato_id_plato', 'ingrediente_id_ing')},
            },
        ),
        migrations.CreateModel(
            name='DetalleInsumos',
            fields=[
                ('id_det_ins', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_det_ins', models.CharField(max_length=50)),
                ('valor_ing', models.IntegerField()),
                ('ingrediente_id_ing', models.ForeignKey(db_column='ingrediente_id_ing', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.Ingrediente')),
                ('proveedor_id_proveedor', models.ForeignKey(db_column='proveedor_id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.Proveedor')),
            ],
            options={
                'db_table': 'detalle_insumos',
                'unique_together': {('id_det_ins', 'ingrediente_id_ing', 'proveedor_id_proveedor')},
            },
        ),
        migrations.CreateModel(
            name='DetPago',
            fields=[
                ('precio_unidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('direccion_entrega', models.CharField(max_length=50)),
                ('pago_id_pago', models.ForeignKey(db_column='pago_id_pago', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='OrderFood.Pago')),
                ('pedido_id_pedido', models.ForeignKey(db_column='pedido_id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.Pedido')),
                ('repartidor_id_repartidor', models.ForeignKey(db_column='repartidor_id_repartidor', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.Repartidor')),
            ],
            options={
                'db_table': 'det_pago',
                'unique_together': {('pago_id_pago', 'pedido_id_pedido')},
            },
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('tipo_plato', models.CharField(max_length=50)),
                ('estilo_comida', models.CharField(max_length=50)),
                ('restaurant_id_restaurante', models.ForeignKey(db_column='restaurant_id_restaurante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='OrderFood.Restaurant')),
                ('enc_cocina_id_enc_cocina', models.ForeignKey(db_column='enc_cocina_id_enc_cocina', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.EncCocina')),
                ('plato_id_plato', models.ForeignKey(db_column='plato_id_plato', on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.Plato')),
            ],
            options={
                'db_table': 'carta',
                'unique_together': {('restaurant_id_restaurante', 'plato_id_plato')},
            },
        ),
    ]
