# Generated by Django 3.2.9 on 2021-11-30 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajero',
            name='restaurant_id_restaurante',
        ),
        migrations.AddField(
            model_name='cajero',
            name='restaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrderFood.restaurant'),
            preserve_default=False,
        ),
    ]
