# Generated by Django 2.2.13 on 2021-10-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
