# Generated by Django 3.2.9 on 2021-11-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
