# Generated by Django 3.2.8 on 2021-11-30 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='comuna_rest',
        ),
        migrations.AddField(
            model_name='cajero',
            name='restaurant_id_restaurante',
            field=models.ForeignKey(db_column='restaurant_id_restaurante', default=1, on_delete=django.db.models.deletion.CASCADE, to='OrderFood.restaurant'),
        ),
    ]
