# Generated by Django 2.2.13 on 2021-10-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenio',
            name='nom_cli',
        ),
        migrations.RemoveField(
            model_name='convenio',
            name='nom_emp',
        ),
        migrations.RemoveField(
            model_name='convenio',
            name='rut_cli',
        ),
        migrations.RemoveField(
            model_name='convenio',
            name='tipo_suscrip',
        ),
        migrations.AddField(
            model_name='convenio',
            name='saldo_cli',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
