# Generated by Django 3.2.7 on 2021-10-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pass_field',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='enc_cocina',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Domicilio',
            field=models.TextField(db_column='direccion_cliente', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.TextField(db_column='password', default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plato',
            name='Imagen',
            field=models.ImageField(default=None, upload_to='platos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cli',
            field=models.CharField(db_column='nombre_cli', max_length=50),
        ),
    ]
