# Generated by Django 3.2.9 on 2021-11-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0002_remove_pedido_horario_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='horario_entrega',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
