# Generated by Django 3.2.9 on 2021-11-10 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0002_alter_plato_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrderFood.categoriaplato'),
        ),
    ]
