# Generated by Django 2.2.13 on 2021-10-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0002_proveedor_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='pass_field',
        ),
        migrations.AddField(
            model_name='administrador',
            name='contraseña1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='contraseña2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
