# Generated by Django 2.2.13 on 2021-10-02 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0003_auto_20211002_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='restaurant_id_restaurante',
            field=models.ForeignKey(db_column='restaurant_id_restaurante', on_delete=django.db.models.deletion.CASCADE, to='OrderFood.Restaurant'),
        ),
    ]
