# Generated by Django 3.2.7 on 2021-11-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0003_alter_plato_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajero',
            name='contraseña1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cajero',
            name='contraseña2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
