# Generated by Django 3.2.9 on 2021-11-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0003_pedido_horario_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='horario_entrega',
            field=models.DateTimeField(),
        ),
    ]
