# Generated by Django 2.2.13 on 2021-10-02 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0004_auto_20211002_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='contraseña1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='contraseña2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='restaurant_id_restaurante',
            field=models.ForeignKey(db_column='restaurant_id_restaurante', default=1, on_delete=django.db.models.deletion.CASCADE, to='OrderFood.Restaurant'),
        ),
    ]
