# Generated by Django 2.2.13 on 2021-10-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0005_auto_20211002_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='email_repartidor',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repartidor',
            name='rut_repartidor',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
