# Generated by Django 2.2.13 on 2021-10-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0007_auto_20211006_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='tipo_veh',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
