# Generated by Django 2.2.13 on 2021-10-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0008_repartidor_tipo_veh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='rut_emp',
            new_name='run_emp',
        ),
    ]
