# Generated by Django 2.2.13 on 2021-10-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0009_auto_20211012_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='run_emp',
            new_name='rut_emp',
        ),
    ]
