# Generated by Django 2.2.13 on 2021-10-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0010_auto_20211012_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='imagen_plato',
            field=models.ImageField(default=1, upload_to='imagenes/platos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[['Pendiente', 'Pendiente'], ['Confirmado', 'Confirmado'], ['En ruta', 'En ruta'], ['Entregado', 'Entregado']], max_length=50),
        ),
    ]
