# Generated by Django 3.2.7 on 2021-10-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0010_auto_20211012_2107'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='plato',
            name='Ingrediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='OrderFood.ingrediente'),
        ),
        migrations.AddField(
            model_name='plato',
            name='Restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='OrderFood.restaurant'),
        ),
        migrations.AddField(
            model_name='plato',
            name='foto',
            field=models.ImageField(null=True, upload_to='plato'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='enc_cocina',
            field=models.ForeignKey(db_column='enc_cocina_id_enc_cocina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='OrderFood.enccocina'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[['Pendiente', 'Pendiente'], ['Confirmado', 'Confirmado'], ['En ruta', 'En ruta'], ['Entregado', 'Entregado']], max_length=50),
        ),
        
    ]
