# Generated by Django 3.2.7 on 2021-10-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0011_auto_20211013_1254'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='plato',
            name='foto',
            field=models.FileField(default=None, upload_to='plato'),
        ),
        
    ]
