# Generated by Django 2.2.13 on 2021-10-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0011_auto_20211012_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='imagen_plato',
        ),
    ]
