# Generated by Django 3.2.7 on 2021-10-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0013_auto_20211013_1536'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='plato',
            name='Imagen',
            field=models.ImageField(default=None, upload_to='plato'),
        ),
        
    ]
